### ISSUE TITLE
agent-config.yaml: hosts parameter is not optional as stated in the docs

### ISSUE THREAD

**Issue by rchakode** [openshift/assisted-installer-agent#527]
Hi,
According to the OpenShift documentation, the `hosts` parameters is optional in `agent-config.yaml` file : https://docs.openshift.com/container-platform/4.12/installing/installing_with_agent_based_installer/installing-with-agent-based-installer.html

Though with the following configuration I'm experiencing a crash when creating the ISO image.

The error does not occur if I add `hosts`. 
If I add `hosts`, that works. However, my need is to create the boot ISO to create my VMs from vSphere with DHCP. 

```
apiVersion: v1alpha1
metadata:
  name: cluster-yxdn
rendezvousIP: 10.0.155.74
```

Error message
```
DEBUG     Fetching Agent Manifests...
DEBUG       Fetching Agent PullSecret...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating Agent PullSecret...
DEBUG       Fetching InfraEnv Config...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG         Fetching Agent Config...
DEBUG         Reusing previously-fetched Agent Config
DEBUG       Generating InfraEnv Config...
DEBUG       Fetching NMState Config...
DEBUG         Fetching Agent Config...
DEBUG         Reusing previously-fetched Agent Config
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating NMState Config...
DEBUG       Fetching AgentClusterInstall Config...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating AgentClusterInstall Config...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/agent/manifests.(*AgentClusterInstall).Generate(0xc000ae6310, 0x5?)
        /go/src/github.com/openshift/installer/pkg/asset/agent/manifests/agentclusterinstall.go:185 +0xe85
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca60, 0xc000ae6310}, {0xc000ac63aa, 0x6})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:227 +0x5fa
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca90, 0xc0002d4620}, {0xc000a4d00c, 0x4})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca30, 0xc0009ffb30}, {0x4bf26f2, 0x2})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x7f616b57a918, 0x1dbb22a0}, {0x0, 0x0})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0x7ffd48a143f2?, {0x7f616b57a918, 0x1dbb22a0}, {0x1db7f9c0, 0x3, 0x3})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x48
main.runTargetCmd.func1({0x7ffd48a143f2, 0x7f})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:261 +0x125
main.runTargetCmd.func2(0x1db8cce0?, {0xc0009c90b0?, 0x3?, 0x3?})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:291 +0xe7
github.com/spf13/cobra.(*Command).execute(0x1db8cce0, {0xc0009c9050, 0x3, 0x3})
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042e280)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:918
main.installerMain()
        /go/src/github.com/openshift/installer/cmd/openshift-install/main.go:61 +0x2b0

```

**Comment by rchakode** [comment]
Closed by creating an issue for openshift-installer: https://github.com/openshift/installer/issues/7003
